### ISSUE TITLE
InfoSec: Blur effect, source code, HTTPS

### ISSUE THREAD

**Issue by edward-shen** [dajinchu/TRACE#9]
Heyo,

SearchNEU contributor here with some knowledge of what's expected of the InfoSec required. 
I don't know if you've talked to the info sec team, but there are a variety of problems as of right now that might pose a problem:

- [x] Blur effect is simply a css effect, data is shown in rendered HTML. Anyone can scrape your website for actual numbers.
- [x] [backend/api/prof/index.js](https://github.com/dajinchu/TRACE/blob/master/backend/api/prof/index.js) straight up shows what appears to be an example your data from your backend.
- [x] You're communicating with trace.sandboxneu.com over HTTP, which means somewhere on the internet you're piping your data through an insecure channel. There is absolutely zero reason why this isn't done over HTTPS via [Let's Encrypt](https://letsencrypt.org/).

All three issues can be seen as InfoSec violations, which could put you at risk of violating Privacy Policy at NU. 

Please be careful and consider putting in stronger measures of authorization. SearchNEU doesn't need to protect against this because all SeachNEU does is format already public data. TRACE data is not public, so any leakage may be a big problem.

**Comment by dajinchu** [comment]
Hey Eddie. thanks for the comments!
1. The numbers that get blurred are all random numbers.
2. Those are random numbers as well. However, you are correct that there is sample data sitting around elsewhere in the repo that needs to be purged.
3. On the todo list - thanks for pointing it out

Please follow up if there's more issues that you find. Really hoping to have the security on this project hardened.

**Comment by edward-shen** [comment]
Alright, that's reassuring to hear; I didn't want y'all to get in trouble! I'm glad those are just random numbers. I'll let you know if I see anything else suspicious.

**Comment by ryandrew14** [comment]
Thanks Eddie! The http thing is one of the last remenants of the hastily written hackathon code that this started from. Good catch on that, and thanks for reviewing the code - this https fix is at the top of our priority list, as security is a top priority for us. We really appreciate the code review, so thanks! If you're interested in helping out more on this you can email me at drew.r@husky.neu.edu if you want to know more about our plans for the future, or just open up issues as you see fit.

**Comment by ryandrew14** [comment]
All infosec issues within this issue are closed out, the last of which by 0fcc1d2a106ab4f1911c297e1ce66588ddbd97f4.
